/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scanTest;

import java.io.File;
import java.io.IOException;

public class Library {
    public boolean someLibraryMethod()  {
        try {
            File.createTempFile("a", null);
            File.createTempFile("a" + "b", null);
            File.createTempFile("aaaaaaaaakjajakjakajakjab", null);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return true;
    }
}
